### ISSUE TITLE
Version for release 1.5 not increased

### ISSUE THREAD

**Issue by Finii** [madmalik/mononoki#100]
The version in the font file is still 1.004; it has not been increased with the 1.5 release to 1.005.

![image](https://user-images.githubusercontent.com/16012374/213121909-4cd7bcd5-bf04-4e89-85ee-f5162d470ed9.png)

(Came up here: https://github.com/ryanoasis/nerd-fonts/issues/575#issuecomment-1386704977)

**Comment by felis-blue** [comment]
Yes, we realized that the version was not updated for the last release, unfortunately too late to fix it in the 1.5 release.

We might do a version 1.6, to fix this and few other minor issues.

**Comment by felis-blue** [comment]
Version 1.6 will be out in a few days and will have the version number fixed!
