### ISSUE TITLE
dotted zero possible?

### ISSUE THREAD

**Issue by effinsky** [madmalik/mononoki#101]
Would it be possible to request a dotted zero option/stylistic set? Thanks for the font to begin with :)

**Comment by madmalik** [comment]
I took a look at this and it seems pretty straight forward. I added a dotted zero, and i was able to activate it with `"editor.fontLigatures": "'ss01'",` in Visual Studio Code.

<img width="90" alt="image" src="https://user-images.githubusercontent.com/1328396/214438930-556c8249-faa8-4972-9112-0b59113b61eb.png">

That stylistic set will be in the next release!

**Comment by effinsky** [comment]
thanks a bunch :)

**Comment by felis-blue** [comment]
The dotted zero is included in version 1.6

**Comment by effinsky** [comment]
Would it be at all possible to distribute the dotted zero set as a separate download? Much easier to use without having to figure out how to enable some stylistic set in ITerm2 or wherever else :) If not, all good, if so, thanks a bunch!
