### ISSUE TITLE
Would you consider supporting vietnamese characters?

### ISSUE THREAD

**Issue by ModProg** [madmalik/mononoki#102]
That would mean adding support for:
- Đ đ which is already included in mononoki I think
- the additional vowls: Ă ă Ơ ơ Ư ư
- the additional diacrits for the vowls (A/a, Ă/ă, Â/â, E/e, Ê/ê, I/i, O/o, Ô/ô, Ơ/ơ, U/u, Ư/ư, Y/y) `0300` [◌̀](https://en.wikipedia.org/wiki/%CC%80) `0301` [◌́](https://en.wikipedia.org/wiki/%CC%81) `0302` [◌̃](https://en.wikipedia.org/wiki/%CC%83) `0309` [◌̉](https://en.wikipedia.org/wiki/%CC%89) and `0323` [◌̣](https://en.wikipedia.org/wiki/%CC%A3)

In total that would be the vowls, though some are already in mononoki:
- A/a, Ă/ă, Â/â, E/e, Ê/ê, I/i, O/o, Ô/ô, Ơ/ơ, U/u, Ư/ư, Y/y 
- Á/á, Ắ/ắ, Ấ/ấ, É/é, Ế/ế, Í/í, Ó/ó, Ố/ố, Ớ/ớ, Ú/ú, Ứ/ứ, Ý/ý 
- À/à, Ằ/ằ, Ầ/ầ, È/è, Ề/ề, Ì/ì, Ò/ò, Ồ/ồ, Ờ/ờ, Ù/ù, Ừ/ừ, Ỳ/ỳ
- Ả/ả, Ẳ/ẳ, Ẩ/ẩ, Ẻ/ẻ, Ể/ể, Ỉ/ỉ, Ỏ/ỏ, Ổ/ổ, Ở/ở, Ủ/ủ, Ử/ử, Ỷ/ỷ 
- Ã/ã, Ẵ/ẵ, Ẫ/ẫ, Ẽ/ẽ, Ễ/ễ, Ĩ/ĩ, Õ/õ, Ỗ/ỗ, Ỡ/ỡ, Ũ/ũ, Ữ/ữ, Ỹ/ỹ 
- Ạ/ạ, Ặ/ặ, Ậ/ậ, Ẹ/ẹ, Ệ/ệ, Ị/ị, Ọ/ọ, Ộ/ộ, Ợ/ợ, Ụ/ụ, Ự/ự, Ỵ/ỵ

**Comment by ModProg** [comment]
I can totally understand if not as this is probably more of a niche usage.

**Comment by madmalik** [comment]
This seems doable. I'm gonna have a look and see if i manage to get those in for the next release :)

**Comment by madmalik** [comment]
@ModProg I took a stab at the additional characters. This is what they are looking like right now:

<img width="1057" alt="Bildschirm­foto 2023-02-19 um 14 20 11" src="https://user-images.githubusercontent.com/1328396/219950799-745f2090-35c6-43b5-8536-7afe0637a84c.png">

I don't have experience with Vietnamese characters, so any feedback would be appreciated!

**Comment by ModProg** [comment]
I feel the separation between letter/^ and  ◌̉ could be a bit larger, not sure if one would run into space constraints then. 

I feel like putting the accents next to the ^ improves readability for ấ ầ ẩ (though GitHub's font doesn't really help my point here).

![grafik](https://user-images.githubusercontent.com/11978847/219955312-a574a7fc-d36a-473b-a457-0964405cb34c.png)

But that is not really a must and is done differently depending on the font.

![grafik](https://user-images.githubusercontent.com/11978847/219955563-b7b89450-3498-4f98-b712-8a5c50a252fc.png)

**Comment by madmalik** [comment]
I agree about the positioning of the hook. I can't space it out further, but i've  redrawn it to be a bit smaller. I think this looks better. What do you think?

<img width="1058" alt="Bildschirm­foto 2023-02-19 um 17 06 44" src="https://user-images.githubusercontent.com/1328396/219960116-41fd61ae-94d3-4c25-a7d5-fe96687576fb.png">

I've also tried to move the accents off to the side, but in the context of monospace constraints it doesn't work out well unfortunately. So i think i'm going to have to keep it like it is now.

**Comment by ModProg** [comment]
This looks great! Again, thanks a lot.

**Comment by felis-blue** [comment]
The new characters are included in Version 1.6
