### ISSUE TITLE
[Question] How can I use dot zero in kitty terminal?

### ISSUE THREAD

**Issue by haunt98** [madmalik/mononoki#104]
Kitty support ligatures in `font_features` config: https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.font_features

But when I try to use like this:

```
font_features mononoki +ss01
```

It does not work :(

**Comment by felis-blue** [comment]
Sorry to hear it, unfortunately we can't really help with specific software configuration, since we don't know your terminal software. Please contact them for help with this issue!

**Comment by haunt98** [comment]
Thanks @felis-blue but I figure it out!

Kitty config need to add this:

```txt
font_features mononoki-Bold +ss01
font_features mononoki-BoldItalic +ss01
font_features mononoki-Italic +ss01
font_features mononoki-Regular +ss01
```

<img width="298" alt="image" src="https://user-images.githubusercontent.com/5424272/221763781-a4f1ab6d-9e97-49a1-b44d-0af06c9e0bef.png">
