### ISSUE TITLE
Where Do I Donate

### ISSUE THREAD

**Issue by DevynCJohnson** [madmalik/mononoki#111]
I understand this is not a real "bug". However, I visually scanned the Mononoki website and this GitHub repo and I did not quickly see where to donate. I have donated in the past and I intend to continue donating a lot as I understand quality fonts do not grow on trees fed with love and peace. The Mononoki font is my favorite font that I use (and require) on every machine that I must work on. In my opinion, this font must be not only maintained to the highest quality, but expanded as well. You know what they say, fonts do not maintain and expand themselves, so where is the official place to donate? I prefer to show my support with action and not words, so please satisfy my request so that I may entice and encourage this fine font to prosper.

**Comment by SwooshyCueb** [comment]
I think the website does contain a paypal tip jar link

**Comment by DevynCJohnson** [comment]
@SwooshyCueb , I hope you are not like most people and can take this constructively, 

I mentioned that I scanned the website and did not see it. For one to state that one _thinks_ the website has it is not an answer. An answer would be (for example), "on the official website, go half-way down on the home page and the PayPal donate button is on the left". Such an example (if true and not an example), would be an answer. I asked a question that requires an answer - not a thoughts.

**Comment by SwooshyCueb** [comment]
On the website, press F3 and search for "tip jar"

**Comment by DevynCJohnson** [comment]
@SwooshyCueb , thanks. That is the style I like.

**Comment by felis-blue** [comment]
Dear Devyn, i hope _you_ take this constructively: If most people think that your feedback is not constructive, then you might consider that the problem is not with them but with your feedback. I suggest you try a bit less self-importance and entitlement next time and see if people's reactions improve.
