### ISSUE TITLE
Why change open/close braces from monoOne?

### ISSUE THREAD

**Issue by seanlaguna** [madmalik/mononoki#13]
Hi, just updated from monoOne. My biggest beef so far with the new font (which otherwise looks nice, I especially like the simpler lowercase a and similar changes) is the more stylized {} characters. (I also noticed the mismatched parenthesis problem, which I am also noticing on every font size I have tested.) Why did you change this from the monoOne version? One of the reasons I loved the monoOne font was because of the extremely plain yet clear curly braces. Similar question about the ? character -- it seems *more* stylized now than it was before, where I enjoyed the simplicity of the monoOne version.

Not asking for a change, just curious what your design decision was here. Thanks for the great font, been using it since 2013.

**Comment by madmalik** [comment]
Hi

Your comment got me look at the curlys on various displays again. To be honest, I'm not entirely sure why I changed them in the first place... so they are back the way the where now :D

**Comment by bassu** [comment]
I :heart:  the new curly braces! They are gorgeous!

**Comment by madmalik** [comment]
:)

**Comment by jdw1996** [comment]
I really like the new curly braces, too. However, I just noticed today that the old curly braces are still used in the bold and italic versions of the font. Perhaps this was intentional, but I thought I'd point it out.

**Comment by madmalik** [comment]
sorry, i derp a lot these days. fixed

**Comment by jdw1996** [comment]
No problem, it looks great now. Thanks!

**Comment by bassu** [comment]
It's now even more beautiful. I want to hug it (if the pointy edges won't hurt, ha ha :stuck_out_tongue_winking_eye: )

**Comment by mariomeissner** [comment]
Hello! I love mononoki and I use it as my main font. I came here just to ask about the mismatched parenthesis. Are they intentional or a bug?

**Comment by areographe** [comment]
> Hello! I love mononoki and I use it as my main font. I came here just to ask about the mismatched parenthesis. Are they intentional or a bug?

I believe it's a bug, as per #12 . @madmalik any chance you could have another look at this? The parentheses aren't aligned in any software under Cinnamon at the moment, even in the GTK Font Manager. [https://imgur.com/d7PN7My]
