### ISSUE TITLE
Add Esperanto characters

### ISSUE THREAD

**Issue by chungy** [madmalik/mononoki#16]
The following are missing from the present font: Ĉ ĉ Ĝ ĝ Ĥ ĥ Ĵ ĵ Ŝ ŝ Ŭ ŭ

All of them before the ŭ use a circumflex, while the Ŭŭ character uses a breve.

It would be great if these can be added. (Btw, what program is used for the "*.glyphs" file? fontforge doesn't seem to recognize it...)

**Comment by madmalik** [comment]
Hi. This seems doable.

The program is [glyphs](https://glyphsapp.com). But i can export ufo files for fontforge.

I don't have time right now, but i'll do it on the weekend.

**Comment by chungy** [comment]
Looks to be Mac-only, but thanks. I thought editing the source would be the nicest way to submit one. I managed to edit the TTF exports in FontForge without much difficulty, but getting these into upstream would be excellent :-)

**Comment by madmalik** [comment]
It's in the last export

**Comment by chungy** [comment]
Thank you, they work beautifully :)

**Comment by madmalik** [comment]
:)
