### ISSUE TITLE
Does it have support of cyrrilic characters?

### ISSUE THREAD

**Issue by Redwan13** [madmalik/mononoki#19]
subj

**Comment by dkoprov** [comment]
http://take.ms/gT28A

**Comment by madmalik** [comment]
I had support for cyrillic glyphs in a previous version, but people complained that they were all wrong. I just don't know enough about cyrillic to implement them properly. If someone wants to take a shot at it, be my guest ^^

**Comment by ahmogit** [comment]
Hi @Madmalik... It was disappointing to see that you threw in the towel on Cyrillic. Could you possibly
be cajoled into reconsidering? It's a great font, and the problems with Cyrillic are very minor, certainly not "all wrong" as you say above.

 From what I observed when I first played with it, the only problems were one missing glyph (which, as @glebd commented, you could create by just copying another similar glyph, and removing the diacritial mark) and three upper-case glyphs  that were slighly mis-sized.

You've done 99% of the work, don't give up on the last 1% mon! :) 

I would certainly be willing to assist if I can, but I know zip about font design. Maybe some of the others who made positive comments in the other thread would be willing to help too?
