### ISSUE TITLE
Powerline glyphs

### ISSUE THREAD

**Issue by naorunaoru** [madmalik/mononoki#20]
So, yeah. It would be nice to have them. 
I really dig this font.

**Comment by madmalik** [comment]
It's on my todo list for this weekend/the beginning of next week.

**Comment by madmalik** [comment]
Done

**Comment by stas** [comment]
@madmalik I'm trying to test this and I don't see the glyphs. I installed the font, invalidated the cache but vim doesn't pick them. As far as I know I don't have to do anything special, do you mind taking a look?

Thank you in advance.

**Comment by madmalik** [comment]
@stas I've double checked the release, but they are in there, and I know from other people that they installed it from the latest release and the powerline glyphs are working for them.

Some other possibilities: Under OS X, one has to delete a font from the font-book before installing a new version, and restart the application that should render the font.
With Linux, it's inconsistent from distro to distro. In my experience, one has to restart the application, the whole x-server or nothing.

Does your terminal show a missing glyph symbol or just nothing?

**Comment by r3bo0t** [comment]
@madmalik @stas yes, removing it from font-book before installation and installing again works like charm.
thanks @madmalik for such an awesome font 💯

**Comment by stas** [comment]
Sorry guys, my bad. Updating the char-codes helped. Thank you!
