### ISSUE TITLE
Ligatures

### ISSUE THREAD

**Issue by gusaiani** [madmalik/mononoki#21]
Gorgeous font, congrats.

Would love ligatures for it ;).

All the best!

**Comment by madmalik** [comment]
Thanks!

Ligatures in a monospaced font are somewhat problematic. If they are one space wide they screw up the alignment, if they are two spaces wide they look dorky (and some operating systems don't recognize them as monospace anymore)

**Comment by gusaiani** [comment]
Thanks @madmalik.

I use [Fira Code](https://github.com/tonsky/FiraCode) and find it a complete pleasure to use with a full set of ligatures.

**Comment by vasanthdeveloper** [comment]
So, the owner (@madmalik ) basically, doesn't want to implement ligatures. :-1:

**Comment by miguel-martinr** [comment]
Same here, I'd love to use Mononoki with some, at least basic, ligatures like =>, ===, !=, etc...
