### ISSUE TITLE
Actually I don't know how to add it in windows10

### ISSUE THREAD

**Issue by AchillesLy** [madmalik/mononoki#22]
sorry， i'm a little unknowledgable .
the way that i only can get zip file,but i do not know how to get the way to add it into windows 10 system

**Comment by mklein994** [comment]
It's simple, really. The zip file contains files that end with ".ttf". Those are the font files you want to install.

1. Unzip the file.
2. In the extracted folder hold `ctrl` and click on each of the TTF font files.
3. Right-click on the selected files and click `Install`. It may ask for admin privileges; accept those.

Done.
