### ISSUE TITLE
Subjective: lower-case 'j' too offset to the right

### ISSUE THREAD

**Issue by diedummydie** [madmalik/mononoki#27]
![screen shot 2016-05-18 at 3 37 25 pm](https://cloud.githubusercontent.com/assets/1759544/15372455/7845a34a-1d0e-11e6-8d40-be717611da99.png)

**Comment by diedummydie** [comment]
For the sake of contrast, here is the lower-case 'j' from Menlo:

![screen shot 2016-05-18 at 3 38 29 pm](https://cloud.githubusercontent.com/assets/1759544/15372506/b76355fe-1d0e-11e6-9ef1-40ecb744805c.png)

**Comment by madmalik** [comment]
I'm pretty sure that the font in the first screenshot is not mononoki ;)

**Comment by diedummydie** [comment]
Ha, sorry, you're right. That was Monaco. I still think the j feels a little too offset toward the right because of its long serif and descender. To me the stem is important in defining the 'center' of the j. But like I said, that's just my subjective opinion.
