### ISSUE TITLE
Windows 7 says the .ttf files are in an invalid format

### ISSUE THREAD

**Issue by johnwcowan** [madmalik/mononoki#30]
Unfortunately, I have to use Windows 7 for work.

**Comment by madmalik** [comment]
Thanks for the feedback.

Does windows 7 give a more detailed error message? That would be really helpful.

**Comment by johnwcowan** [comment]
It turns out that if you right-click and choose Install it works, whereas if you double-click on it (as I have done with other fonts) it fails.  This probably doesn't matter but should be documented.

**Comment by madmalik** [comment]
weird. maybe i find out what's behind that. but it's great that it works for now
