### ISSUE TITLE
Replacement character displayed for non-breaking spaces

### ISSUE THREAD

**Issue by xelkarin** [madmalik/mononoki#32]
I've noticed the replacement character appearing occasionally in my xterm. I copied it to a file and ran xxd on it, here's the output:

```
00000000: c2a0                                     ..
```
It looks like a UTF-8 non-breaking space and a plain space could probably be displayed for this character.

**Comment by madmalik** [comment]
I just created glyphs for every space in the unicode standard. This will be in the next release, where i'll bundle all bugfixes and additions.

Thanks for the issue!
