### ISSUE TITLE
line spacing

### ISSUE THREAD

**Issue by StephanHartmann** [madmalik/mononoki#34]
Hello,
would it be possible to offer sets with different line spacing for ttf files?

Visual Studio (Full, not Code) doesn't offer a setting to adjust line spacing :(
I like your font very much, but in Visual Studio the line spacing is too small compared to default consolas.

**Comment by madmalik** [comment]
Can you show a screenshot? I don't have access to a windows machine or visual studio right now.

**Comment by StephanHartmann** [comment]
Monoki is "one pixel" higher than default Consolas, I would prefer when there is "another pixel" on top or at bottom of Monoki.

This is Monoki font :
![monoki](https://cloud.githubusercontent.com/assets/10873640/15456403/a8f75eca-206f-11e6-9d26-b8e365ef8fb3.png)
this is Default Consolas :
![consolas](https://cloud.githubusercontent.com/assets/10873640/15456414/ad1fcb36-206f-11e6-9caa-f42b79a16764.png)

Direct Comparison
![compare](https://cloud.githubusercontent.com/assets/10873640/15456423/d5a25682-206f-11e6-92a9-5513cc28239a.png)

**Comment by StephanHartmann** [comment]
I don't know how fonts are build and designed, how much work such an "adjustment" is.
If it is an option in a tool,  it would be great to offer a second set.
If it is a complete rework, then drop this issue -> I'm happy you build and shared this set !

**Comment by madmalik** [comment]
thought about this, but unfortunately it's not really feasible to do!
