### ISSUE TITLE
Polish 'ł' lettter missing.

### ISSUE THREAD

**Issue by BlessJah** [madmalik/mononoki#37]
Unicode Character 'LATIN SMALL LETTER L WITH STROKE' (U+0142) seems to be missing. Rest of polish characters (including capital Ł) are present.

Polish pangram:
    'pchnąć w tę łódź jeża lub ośm skrzyń fig'
    'PCHNĄĆ W TĘ ŁÓDŹ JEŻA LUB OŚM SKRZYŃ FIG'
Gets rendered like this:
![pl](https://cloud.githubusercontent.com/assets/835808/15478390/43fd2e72-211a-11e6-83c3-9b39699ca3fb.png)

**Comment by madmalik** [comment]
Added it. It'll be in the next release. Thank you!

**Comment by BlessJah** [comment]
Thanks a lot. By the way, polish wiki lists multiple pangrams for 21 languages, you might add them to website to let others see that their's national characters are included as well: https://pl.wikipedia.org/wiki/Pangram#Przyk.C5.82ady

**Comment by madmalik** [comment]
good idea!
