### ISSUE TITLE
Descenders cut off on OS X

### ISSUE THREAD

**Issue by jdw1996** [madmalik/mononoki#39]
I've been using the font on OS X at work, and I've noticed some strange behaviour: in some cases, the descenders seem to get cut off.

In the terminal, on most lines the whole characters show, but on the very bottom line they get cut off.
<img width="190" alt="screenshot1" src="https://cloud.githubusercontent.com/assets/17225098/15527677/825136f0-220a-11e6-8dd5-6e901b08da5e.png">

Also, in Emacs, I can see whole characters, but the block cursor doesn't cover all of the descenders.
<img width="68" alt="screenshot2" src="https://cloud.githubusercontent.com/assets/17225098/15527694/992ed580-220a-11e6-8d51-02a5d929cf33.png">

Curiously, this doesn't happen in Emacs on Ubuntu (or in GNOME Terminal, for that matter).

EDIT: This affects the comma and semicolon as well, and potentially other characters I just haven't noticed yet.

**Comment by madmalik** [comment]
I was able to recreate it, and I'm 80% sure where I have to poke to solve it. I'll post here when it's done.

**Comment by jdw1996** [comment]
Awesome, thanks!

**Comment by jdw1996** [comment]
I was thinking about this again today -- perhaps the reason I don't notice the issue on Ubuntu is that the computer I run it on has a screen with much lower resolution than the Mac I use at work.

I don't know if this helps, but I thought I should mention it.

**Comment by madmalik** [comment]
I think this should be solved, if not please reopen
