### ISSUE TITLE
update export files

### ISSUE THREAD

**Issue by grafoo** [madmalik/mononoki#40]
Could someone update the "export bundle" [mononoki.zip](https://github.com/madmalik/mononoki/blob/master/export/mononoki.zip) ?
The parens alignment is driving me nuts :D and a guess a fix for that came with commit [619ba6c](https://github.com/madmalik/mononoki/commit/619ba6cab983cda21bc40d413bc5bf27831f42f9) ?

Don't know anything about fonts or how to create the ttf files myself. Pointing out how to do this without a paid program would also fix my issue ;)

cheers,
manuel

**Comment by madmalik** [comment]
I've updated them.
