### ISSUE TITLE
Italic text rendering at 13pt in Atom

### ISSUE THREAD

**Issue by laughedelic** [madmalik/mononoki#42]
I observe some strange rendering issue for italic text (especially numbers) in Atom (v1.8.0-beta4) OS X:
- 12pt: 
  <img width="272" alt="screen shot 2016-06-03 at 20 32 12" src="https://cloud.githubusercontent.com/assets/766656/15789076/c1920cbe-29ca-11e6-88ff-2173c5688151.png">
- 13pt: 
  <img width="388" alt="screen shot 2016-06-03 at 20 32 20" src="https://cloud.githubusercontent.com/assets/766656/15789097/d13fa18a-29ca-11e6-9e67-05248cc302e0.png">
- 14pt: 
  <img width="312" alt="screen shot 2016-06-03 at 20 32 29" src="https://cloud.githubusercontent.com/assets/766656/15789103/d72b3280-29ca-11e6-9b9e-ac1fc1a4a9c1.png">

UPD: actually I see now that at 13pt it's substituted by some different font 😕

**Comment by laughedelic** [comment]
I just tried Atom 1.7.4 and there is no such issue. I guess, I should report this in the Atom repo.

**Comment by madmalik** [comment]
yeah, it's strange. Font rendering engines are hairy beasts...
