### ISSUE TITLE
Alternative @ glyph

### ISSUE THREAD

**Issue by raphaelokon** [madmalik/mononoki#45]
Hi. I really like Mononoki … it is a fresh and awesome monospace font. One thing I find not optimal is the @ glyph. I redesigned it personally for me, but would like to have your thoughts on it. It is not hinted properly yet. And some details around extrema needs care as well.

<img width="912" alt="mononoki_at" src="https://cloud.githubusercontent.com/assets/527631/17242278/a999483e-5576-11e6-8b49-5c913b8ad2b5.png">

**Comment by CreamyCookie** [comment]
Looks good but I think the charm of Mononoki's @ is that it's a bit thicker and thus makes it more distinct from normal letters. I don't know if this could be done with your @. Of course it's very subjective.

**Comment by madmalik** [comment]
@raphaelokon looks nice!

Some rationale for the current form: I started with a counter in the "a" part like in your version, but that created problems when rendered in low resolution. The @ is just a very complex glyph and prone to be rendered as pixel-mud under certain circumstances. 

Since the @ is a common sigil I opted for a simplified version. So if everybody had a HiDpi Display, I would in include your version or something similar. 

But thanks for posting your version! What program did you use for it?

**Comment by raphaelokon** [comment]
@CreamyCookie Thanks. I see your point. I do not use Mononoki solely for coding … I use it for my documentations and some copy in docs as well – it is much more pleasant for me with the new @. I will dedicated some time and draw it from scratch and balance it out for my needs.

@madmalik Thanks as well :-) I completely agree. I have to draw it from scratch and add hints properly … but there are other great monospace fonts that gets it right … and from a type design perspective the @ is rather boring to do  tbh :)   

> Since the @ is a common sigil I opted for a simplified version. So if everybody had a HiDpi Display, I would in include your version or something similar.

I used a Eizo CG (non-retina) to create the glyph and downsized it to work ~12pt on it and ~10pt on my a retina MBP.

> But thanks for posting your version! What program did you use for it?

Quick sketch on paper → Glyphs2

**Comment by raphaelokon** [comment]
Just for the sake of completeness: Here is an example of the @ on a non-retina at ~12pt in rendered in Atom.

![at](https://cloud.githubusercontent.com/assets/527631/17290050/dcd0beae-57dc-11e6-8d3f-f21f1f570a17.png)

I am closing this issue due to the notes above tho.

**Comment by madmalik** [comment]
I've started to experiment a little more. Maybe something will come of it ;)

**Comment by raphaelokon** [comment]
Cheers :)
