### ISSUE TITLE
Bold Italic is not being grouped as same family in Windows

### ISSUE THREAD

**Issue by potasiyam** [madmalik/mononoki#49]
Hello, first of all thank you so much for creating this beautiful font.
I am using Mononoki in Windows 10. I was selecting Mononoki as default in gVim. In the font choosing dialogue box Mononoki is showing like this-
![capture-1](https://cloud.githubusercontent.com/assets/767359/20660291/08549a8e-b573-11e6-983d-9bf7c87557b7.PNG)

The bold italic variant is out of the family. I checked fonts folder of Windows, bold italic was not there-
![capture-2](https://cloud.githubusercontent.com/assets/767359/20660329/43bb6c2e-b573-11e6-9a18-e855accdbdbd.PNG)

I deleted Mononoki group then the bold italic variant appeared as a single font. I am guessing the issue is somewhere in font naming.

**Comment by richardgv** [comment]
What worked for me on Windows 7 SP1 is:

* Open `mononoki-BoldItalic.ttf` with FontForge.

* Choose "Element" menu -> "Font Info".

* Choose "TTF Names" tab in the appeared "Font Information" window, and remove the "Preferred Styles" entry with its right-click menu.

* Re-export the TTF via "File" menu -> "Generate Fonts".

It seems Windows is extraordinarily picky on many font properties.

**Comment by datMaffin** [comment]
I was able to fix this (and related issues) by renaming the "Fontname" from "mononoki-BoldItalic" to "mononoki-Bold-Italic".
The regex windows seems to use is apparently a bit picky.

**Comment by madmalik** [comment]
I have renamed the bold italic version accordingly. Testing on Windows 10, all styles were then grouped correctly for me, the change will be in the next published version.
