### ISSUE TITLE
[WORKAROUND] Position in the fonts list

### ISSUE THREAD

**Issue by sergeevabc** [madmalik/mononoki#57]
Dear @madmalik,

The following screenshot is taken in Thunderbird / Windows 7.

![](https://pli.io/WoULq.png)

Could you tell why Mononoki does not respect alphabetical fonts sorting and is listed below others?

P.S. Also, a separate placement of **_BoldItalic_** variant looks weird (#49).

**Comment by walston** [comment]
It might be technically alphabetized if thunderbird is using ascii code to sort chars. This would result in caps being sorted before lowercase. Should `mononoki` be capitalized?

**Comment by sergeevabc** [comment]
Since ```mononoki``` is a proper noun, I believe it should be capitalized.

**Comment by walston** [comment]
While I tend to agree, even the [splash page](http://madmalik.github.io/mononoki/) has it written in lower-case.

**Comment by jdw1996** [comment]
You could rename the font files yourself, using [something like this](https://github.com/chrissimpkins/fontname.py), if you wanted.  It would be nicer to have an upstream solution, but this might do as a workaround.

**Comment by sergeevabc** [comment]
Hmm, according to the heatmap, @madmalik is a rare guest here.
I was lucky to find his e-mail address, let’s see if he responds.

**Comment by madmalik** [comment]
Hi everyone. 
Sorry for not being around... I'm in the last stages of finishing a thesis and have very little time right now. Thankfully it's only a few more days.

Getting on top this project again is the first item of my "stuff i do once i defended my thesis" list. ;) Next week you should see some activity.


Sorry again to leave you all hanging.
