### ISSUE TITLE
It seems some special characters are not correctly displayed in Emacs.

### ISSUE THREAD

**Issue by cmal** [madmalik/mononoki#58]
like the square char:

![image](https://user-images.githubusercontent.com/1773318/40832986-329ebd26-65bf-11e8-8023-6691e83a487d.png)

and some chars else(but sorry I've forgot for now). I will submit an update if I met another.

**Comment by madmalik** [comment]
I've since reworked all those super and subscripts. The next release shouldn't have those problems
