### ISSUE TITLE
metadata missing (?) [possible thirdparty problem]

### ISSUE THREAD

**Issue by exvx** [madmalik/mononoki#59]
In a recent update, Gnome changed how their terminal handles font choices. The font choice pop up menu used to display a list of every font in your system for you to choose from, now it filters away all non monospace fonts. It also filters away some monospace fonts, including Mononoki.

I assume the filtering is based on some sort of metadata tag stored in the `.ttf` file. I have no idea how `ttf` work, but I'll update this once I've done some digging in.

Update:
[Office code pro](https://github.com/nathco/Office-Code-Pro) is also affected.

**Comment by roachsinai** [comment]
Hi @exvx , is there any way to let my gnome-terminal use `mononoki`?

**Comment by roachsinai** [comment]
And now I have to let gnome-terminal use system mono font setting by tweak-tool.

**Comment by exvx** [comment]
Not that I'm aware of. That last thing works alright, though it's not ideal. I'll let you know if I come across a solution.

**Comment by manuel-uberti** [comment]
@exvx anything?  :)
