### ISSUE TITLE
Add ligatures similar to Fira Code

### ISSUE THREAD

**Issue by NikilRagav** [madmalik/mononoki#60]
I love the way this font looks. It doesn't have the tail for the a and it has other features that give the font character and make it more readable than other coding fonts. I would love for ligatures to be added just like Fira code has (ex. >= becomes one symbol that is double width != becomes equals sign with slash, also double width)

**Comment by demigor** [comment]
Second to that. Apart from ligatures, mononoki is the best code font at the moment.

**Comment by madmalik** [comment]
See #29.
