### ISSUE TITLE
Possible funding to add mathematical symbols to Mononoki 

### ISSUE THREAD

**Issue by Cubesoup** [madmalik/mononoki#63]
Greetings,

I'm a research assistant at the University of Edinburgh (specifically the Blockchain Technology Lab), and am currently in the process of putting together a proposal to fund the addition of certain mathematical symbols to a font for use with text editors.

Recent experiences with the book ["Programming Language Foundations in Agda"](https://plfa.github.io/) have really made us want a single, monospaced, font that we can just tell people to use (and use ourselves for development!). Mononoki is, in my opinion, the most promising candidate for this (great work!). The font can of course remain open source, and we'd really like to involve you (@madmalik) in at least some capacity (can't figure out how to contact you directly!). 

Right now, we're trying to get an estimate of how much it would cost and how long it would take to add the symbols we'd like so that we can ask for money (list of symbols follows). Please contact me by email at cnester@ed.ac.uk when you can so that we can explore options!

List of symbols we'd like (possibly more, depends on cost): 
  U+2192 (double-struck capital n)
  U+2200 (for all)
  U+2203 (there exists)
  U+2192 (rightwards arrow)
  U+2190 (leftwards arrow)
  U+2194 (left right arrow)
  U+21D2 (rightwards double arrow)
  U+21D0 (leftwards double arrow)
  U+21D4 (left right double arrow)
  U+21A0 (rightwards two headed arrow)
  U+219E (leftwards two headed arrow)
  U+2191 (upwards arrow)
  U+2193 (downwards arrow)
  u+2262 (not identical to)
  U+225F (questioned equal to)
  U+2250 (approaches the limit)
  U+2238 (dot minus)
  U+2243 (asymptotically equal to)
  U+22A4 (down tack)
  U+22A3 (left tack)
  U+22A5 (up tack)
  U+22A2 (right tack)
  U+2227 (logical and)
  U+2228 (logical or)
  U+2283 (superset of)
  U+2297 (circled times)
  U+2218 (ring operator)
  U+2237 (proportion)
  U+2294 (square cup)
  U+228E (multiset union)
  U+2225 (parallel to)
  U+2208 (element of)
  U+2209 (not an element of)
  U+220B (contains as member)
  U+220C (does not contain as member)
  U+2272 (less than or equivalent to)
  U+2273 (greater than or equivalent to)
  U+2605 (black star)
  U+2982 (z notation type colon)
  U+019B (latin small letter lambda with stroke)
  U+27E8 (mathematical left angle bracket)
  U+27E9 (mathematical right angle bracket)
  U+230A (left floor)
  U+230B (right floor)
  U+220E (end of proof)
  U+207A (superscript plus sign)
  U+207B (superscript minus)
  U+02B3 (modifier letter small r)
  U+02E1 (modifier letter small l)
  U+1D9C (modifier letter small c)
  U+1D47 (modofier letter small b)
  U+2099 (latin subscript small letter n)
  U+1D62 (latin subscript small letter i)
  ... plus superscript and subscript digits 0-5
  ... possibly other superscript and subscript letters, digits.

**Comment by datMaffin** [comment]
I went through the list and the only glyph missing seems to be "U+1D62 (latin subscript small letter i)"

**Comment by madmalik** [comment]
Oh, good call. I've added it.
