### ISSUE TITLE
'ď' looks non-standard which might lead to confusion

### ISSUE THREAD

**Issue by anymouse404** [madmalik/mononoki#66]
Hi,
The problem is with the symbol 'ď', that is, 'd' with 'ˇ'. Normally, and I'm pretty sure what you can see it here, even though ď is written using the 'ˇ' key, how it is displayed looks more like with apostrophe. This is correct in Mononoki, however normally the 'ˇ' sign is on the right of the letter (I've never seen otherwise), but in Mononoki it is on the left of the character. 
This can lead to confusion, where when there is 'd' and 'ď' symbol next to each other, user can misunderstand which symbol the 'ˇ' is for. This is visible in attached picture which show the same text in different fonts.
![image](https://user-images.githubusercontent.com/49173322/62628791-45aa5080-b92c-11e9-8b2c-d37096664ae1.png)

**Comment by madmalik** [comment]
I've found a solution to cram a mark onto the correct side and stay in the monospace grid. It'll be in the next release.

(sorry for the late answer, i had a lot going on...)

**Comment by madmalik** [comment]
its fixed in the current version
