### ISSUE TITLE
Bundling Mononoki font with Lite XL ?

### ISSUE THREAD

**Issue by franko** [madmalik/mononoki#71]
Hi,

I am currently working on the [Lite XL](https://github.com/franko/lite-xl) editor, derived from [Lite](https://github.com/rxi/lite). For Lite XL I have essentially improved the rendering of the fonts using state-of-the-art subpixel font rendering.

The original project, Lite, is using the Roboto Mono for the code but I love the look of the Mononoki font, especially with the dark theme of Lite.

I was wondering if you are ok if I bundle the Mononoki font, the regular one, with the next release of Lite XL ?
In any case I would appreciate to have your advice. If you want you may have a look to the Lite XL editor and the rendering of the Mononoki fonts. In addition I am wondering what proportional font I may couple with Mononoki.

You can try Lite XL from [there](https://github.com/franko/lite-xl/releases/tag/v1.08-subpixel). In order to use the mononoki font with the editor you need to add the line

```lua
style.code_font = renderer.font.load("c:/francesco/local/share/fonts/mononoki-Regular.ttf", 20 * SCALE)
```
in the file `data/user/init.lua`.

In any case I would greatly appreciate your advice as a typography expert, thank you in advance.

**Comment by madmalik** [comment]
Of course you can use and bundle the font :)

A good pairing would be Open Sans https://fonts.google.com/specimen/Open+Sans#standard-styles. Its also under a free license.

Sadly, i don't have access to a Windows or Linux machine in the moment so i cannot try Lite XL for myself. But it seems like you're using freetype2 and that should render just fine.

**Comment by franko** [comment]
Hi Matthias,

thank you for your message, I am glad you are ok to bundle the mononoki font with Lite XL.

I guess you are on a Mac OS X, this is unfortunately the only main OS I don't have access to but I am thinking about getting one to address people using Mac OS X when publishing an application.

So I think I may close this "issue", thank you.

**Comment by franko** [comment]
Lite XL screenshots using mononoki and Open Sans fonts.

I like how they match, I think they have a "rounded" nature that goes well together.

Dark theme:
![Lite-XL-dark-theme-mononoki-open-sans](https://user-images.githubusercontent.com/433545/85391152-1a335300-b54a-11ea-86d9-24cfe978e60d.PNG)

Light theme:
![Lite-XL-light-theme-mononoki-open-sans](https://user-images.githubusercontent.com/433545/85391166-1f909d80-b54a-11ea-87ae-7a79871f698f.PNG)
