### ISSUE TITLE
Update of mononoki font for PLFA

### ISSUE THREAD

**Issue by wenkokke** [madmalik/mononoki#72]
Thanks so much for the changes you made to mononoki for PLFA!

However, it doesn't seem like you pushed those changes to the main repository.

We're encouraging readers to visit the mononoki website to download and install the font, but it's causing some confusion when some characters that *do* render in their browser, don't render in their text editor.

Would you be willing to include the changes in the published version of mononoki?

**Comment by madmalik** [comment]
Sorry I thought I had updated it! I will publish a new version soon that will contain all changes!
