### ISSUE TITLE
Extra space after ≢(U+2262)

### ISSUE THREAD

**Issue by vu3rdd** [madmalik/mononoki#76]
The U+2262 is rendered with a trailing extra space. That seem unnecessary and look like a bug?

Thanks for the nice font.

**Comment by datMaffin** [comment]
I don't think that there is a U+2262 in the mononoki font:
![image](https://user-images.githubusercontent.com/29998721/124396975-3517d600-dd0d-11eb-9c72-f6b63d55fed3.png)
(the field is empty)
