### ISSUE TITLE
The height of the left and right brackets is inconsistent.

### ISSUE THREAD

**Issue by SeehopeHuang** [madmalik/mononoki#77]
It seems that the height of the left and right brackets is inconsistent when I set the font size to 10 (or some other sizes) in Windows10:
![1](https://user-images.githubusercontent.com/41578590/107872737-4ccdf980-6ee7-11eb-9731-7520eb0d078d.png)
but it works right in some sizes:
![2](https://user-images.githubusercontent.com/41578590/107872743-59525200-6ee7-11eb-8eed-6a1d7a13169f.png)
Love this font, thanks : )

**Comment by ad1tyawagh** [comment]
Yes, please fix this.

**Comment by madmalik** [comment]
Please see issue #79. I'm gonna track it there
