### ISSUE TITLE
Missing and shrimpy Cyrillic glyphs

### ISSUE THREAD

**Issue by ahmogit** [madmalik/mononoki#8]
I like your font, very nice for programming and general use... but for the latter, noticed that the Cyrillic (Russian) 'И' glyph is missing.  Also, upper-case 'Г'  and 'У' are both noticeably smaller than other upper-case characters. Upper-case Ф is also a little bit small, but less noticeably than Г and У.  See screenshot.

Hope you have time to fix these, and thanks for the great font!
![examp](https://cloud.githubusercontent.com/assets/5025879/2751256/ac8e9974-c8bd-11e3-95c7-8d4e2444e00b.jpg)

**Comment by ahmogit** [comment]
Hi again... just a friendly ping to ask if you're planning to continue work on this font? It's really a nice font and I'd like to replace a lot of my existing font usage with it, because imo it's cleaner and better
designed that all of the other common monospace fonts I've tried. Unfortunately, the missing Cyrillic 'И'  glyph makes it unusable. (The shrimpy г and у can be lived with.) So I was wondering if you could be enticed to at least just fix the missing glyph?  Wold really appreciate it!  Thanks!

**Comment by glebd** [comment]
You could just use 'й' to make 'и'. Otherwise it looks like this: 
![screen shot 2015-09-04 at 21 56 45](https://cloud.githubusercontent.com/assets/32538/9694402/4c846d1e-5350-11e5-9716-87fc2ce1676a.png)

**Comment by donangel** [comment]
Great font! +1 for Cyrillic!

**Comment by madmalik** [comment]
see https://github.com/madmalik/mononoki/issues/19

**Comment by ahmogit** [comment]
Hey @glebd , @donangel:  See my comments in #19. Maybe we can help him to fix the minor problems?
It would be a shame to see all the effort @madmalik put in on it go to waste. As far as I could tell, only a few minor tweaks were needed. Did you guys notice anything more serious?

**Comment by glebd** [comment]
It's a bit of a problem that the font was designed in Glyphs which looks like a great font designer app but is not cheap for an occasional tweaking of an open-source font.

**Comment by ahmogit** [comment]
On Wed, May 18, 2016, at 16:13, Gleb Dolgich wrote:
> It's a bit of a problem that the font was designed in Glyphs which looks like a great font designer app but is not cheap for an occasional tweaking of an open-source font.
> 

Educate me here, I know less than nothing about font design or the associated tools.
Is "Glyphs" a tool that you have to pay for by each usage, or something like that?

**Comment by glebd** [comment]
https://glyphsapp.com is a Mac app which, judging by the type of the font source file, was used to design it.

**Comment by madmalik** [comment]
my post was a little bit harsh, sorry. i've rerread the old issue and the problems are not that serious as i had remembered them. also, i'm a little bit overwhelmed right now by the sudden interest by so many people ^^

i have some free time on the weekend and next week. i'll look into some material about Cyrillic and into other typefaces for reference and i'll try my best.

**Comment by artfwo** [comment]
@madmalik thanks for looking into it!

**Comment by madmalik** [comment]
about glyphs: i used fontforge in the past, but glyphs is just sooo much nicer to use. but i know that it's suboptimal for an open source font, since it's mac only and not cheap (and closed source)

i could make ufo exports that could be opened by fontforge, but i'll have to come up with a plan to get additions upstream. 

maybe i make a fontforge or ufo version where people can make additions, and i incorporate them with the additional weights and tweaks into the "mainline".
I'll put some thought into that

**Comment by madmalik** [comment]
I painted the base glyphs from scratch. Does this look ok?
<img width="692" alt="ohne titel" src="https://cloud.githubusercontent.com/assets/1328396/15505064/2a554a92-21c2-11e6-92c1-18d3e5cf53cc.png">

**Comment by donangel** [comment]
"Х" is a bit strange...

**Comment by artfwo** [comment]
Cyrillic "Х" seems to be the same shape as Latin "X" and it's okay.
Ъ and Ь could possibly be improved if the lower arc had the same width in both characters.
The tail in Щ might look better if it was the same width/shape as in Ц.
Lowercase г looks a bit wide to me.

**Comment by madmalik** [comment]
Thanks for the feedback!

**Comment by glebd** [comment]
Amazing, excellent work!

**Comment by ahmogit** [comment]
Nice job @madmalik, thanks for revisiting this and for all your work on it. Great font.
Looks like you've got quite a few people who are glad you didn't give up on it! +1.

I agree with the few minor tweaks mentioned by @artfwo. But I would be happy to use it even as-is.
Thanks again.
