### ISSUE TITLE
Added math glyphs in preview look unfinished in italic/bold

### ISSUE THREAD

**Issue by datMaffin** [madmalik/mononoki#83]
See (looks similar for bold and bold-italic):
![image](https://user-images.githubusercontent.com/29998721/129477570-a51ef5ce-3e0c-47d8-aca7-3bbf73ae5246.png)
A few number just stick out/dont fit

Also (looks similar for bold and bold-italic):
![image](https://user-images.githubusercontent.com/29998721/129477586-e7f983eb-1653-438e-84d1-69a7cbea8572.png)
Some numbers are misaligned.

There might be some more glyphs where something similar went wrong.

**Comment by madmalik** [comment]
I corrected the math glyphs. They will be in the next release. Thanks for the catch!

**Comment by datMaffin** [comment]
I am curious why your fixes appear to not have landed in the exported ttf...

The fractions still look weird:
![image](https://user-images.githubusercontent.com/29998721/189535692-75836bea-742d-4a60-88c3-14c34ad39ee4.png)

Also, the superscript now use the new glyph form, but the height of the superscript 5,6,7,8,9 is too low:
![image](https://user-images.githubusercontent.com/29998721/189535804-7a436ad7-5567-450c-8eab-f873fd9f3d8f.png)

Bold and Bold-Italic seem to have the same issues.

**Comment by madmalik** [comment]
Irks, that's on me. I thought I had exported it with the correct component composition. I've done it now and updated the exports.
