### ISSUE TITLE
CMD not showing some characters

### ISSUE THREAD

**Issue by alu0101330105** [madmalik/mononoki#85]
I've been trying to fix this thing for a while, and I just couldn't, so I gave up. Until I saw that in Vscode terminal with the same font is working as intended.

Problem:
What I get in cmd (with bash, but same if I do tree in normal cmd)
![image](https://user-images.githubusercontent.com/92103280/143231153-89ee4ac6-37f7-4ab9-83a7-0b992ded3544.png)

What I get in vscode terminal (with same bash)
![image](https://user-images.githubusercontent.com/92103280/143231100-68960127-3bbf-4594-bfc7-be9cc9ef2dbc.png)

![image](https://user-images.githubusercontent.com/92103280/143231265-d2f9afc7-22fa-4b7c-86ed-375875ab3cbe.png)
I do have the mono variant, but the regular behaves the same way

and just to be sure I tried different nerd fonts just to see and with Hack seems to be working just fine
![image](https://user-images.githubusercontent.com/92103280/143231580-01645b1d-1856-453b-a79b-e67c9b360fc4.png)

There are other characters that doesn't show correctly but then devicons works just fine

In here there should be a > thingie and then there is the devicon 
![image](https://user-images.githubusercontent.com/92103280/143231999-03c1fa01-a0df-4283-828d-0fc636d29abf.png)

## quick edit:
I also tried changing the encode but just did not work, and as far as I know unless its UTF-8 it should not show the devicons

**Comment by datMaffin** [comment]
I would guess that this is related to #50 

VsCode is probably using a fallback font for this missing glyph.

**Comment by datMaffin** [comment]
Pretty sure that #50 is the only thing missing for the box drawing.
VsCode uses by default their own box drawing (it completely disregards the box drawing glyphs that are included in the font); which is why it looks perfect in the VsCode screenshot.

Regarding the ">" thingie would still missing, an exact unicode number or name would be required from @alu0101330105

**Comment by madmalik** [comment]
I think you're right @datMaffin! Thanks for looking into this!

I will close this issue since the box character has been added. OP, please reopen with more information if there are still characters missing.
