### ISSUE TITLE
Update website example to Python 3

### ISSUE THREAD

**Issue by dancojocaru2000** [madmalik/mononoki#87]
Python 2 is discontinued, no longer receiving updates, and to be avoided unless absolutely necessary. Not even security fixes will be provided.

Considering this, the example on the website should be updated to Python 3:

```py
# how to ace an interview
for i in range(1, 101):
    if i % 15 == 0:
        print("mononoki")
    elif i % 3 == 0:
        print("mono")
    elif i % 5 == 0:
        print("noki")
    else:
        print(i)
```

**Comment by madmalik** [comment]
Since the website was updated the code example is modernized :)
