### ISSUE TITLE
Subscript numbers look off compared to each other when italicized

### ISSUE THREAD

**Issue by ThePuzzlemaker** [madmalik/mononoki#88]
Here is U+2080-U+2089, italicized (top) and regular (bottom):
![image](https://user-images.githubusercontent.com/12666617/153695666-6e83e18b-a136-48d7-b5a4-a8413fd8867a.png)
As you can probably see some of these look off and are different when italicized.

**Comment by madmalik** [comment]
Good catch! I've corrected those glyphs
