### ISSUE TITLE
Add powerline extended?

### ISSUE THREAD

**Issue by Auratelience** [madmalik/mononoki#90]
Basically just looking for the round powerlines blocks.
Thanks, Auratelience

**Comment by vallyscode** [comment]
There is a patched version with powerlines + other symbols in nerd fonts repo
https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Mononoki

**Comment by Auratelience** [comment]
Oh cool. Thanks

**Comment by madmalik** [comment]
I have added some of the symbols. I have drawn them a bit more in mononoki style then the originals. They are gonna be in the next release.
<img width="479" alt="image" src="https://user-images.githubusercontent.com/1328396/202856636-f081dff0-b9b9-470e-8e13-cec12c12ce27.png">

**Comment by Auratelience** [comment]
Cool. Thanks.
