### ISSUE TITLE
Shape inconsistencies in bold-italic "J" and bold-italic "r"

### ISSUE THREAD

**Issue by datMaffin** [madmalik/mononoki#91]
As there recently is more activity, here two shape inconsistencies I noticed ;) :
* The italic and bold-italic "J" use a different shape. I would have expected that the italic shape is also used for the bold italic shape: 
![image](https://user-images.githubusercontent.com/29998721/188697788-bc195651-aa23-4159-a1c0-35f7b8e309f1.png)
* The width of the stem of the bold italic "r" was 15 bigger than I expected: 
![image](https://user-images.githubusercontent.com/29998721/188699724-3fc03a63-0d4f-42e2-85bd-4d66b3572e45.png)

*The screenshots were made using the most recent ttfs in the export folder on the main branch.*

**Comment by madmalik** [comment]
Thanks for the observation! Its fixed.
