### ISSUE TITLE
Small sharp s ß is not as tall as expected

### ISSUE THREAD

**Issue by datMaffin** [madmalik/mononoki#92]
I noticed the capital ß in Mononoki and remembered that there was something off with the Mononoki ß 😉  ;

I would have expected the ß to be as high as all the other lower case letters that are the full height:
![image](https://user-images.githubusercontent.com/29998721/189495905-6d2365af-49df-41dd-87ec-e7b9b2ffd09f.png)

Consolas for comparison:
![image](https://user-images.githubusercontent.com/29998721/189496737-9d17eebb-079f-4a7c-a83e-8f195a07a5cd.png)

**Comment by madmalik** [comment]
Your are right! I've redrawn it :)
