### ISSUE TITLE
Polish "K" connections to look similar to lower case k

### ISSUE THREAD

**Issue by datMaffin** [madmalik/mononoki#93]
How it looks currently:
![image](https://user-images.githubusercontent.com/29998721/189496861-d4bef9c2-67f5-489d-8946-a51c9a6b7757.png)

How it would look with polished intersections:
![image](https://user-images.githubusercontent.com/29998721/189496875-f6f497f1-07a5-47d0-b128-d336d1198758.png)

**Comment by madmalik** [comment]
Mhh, that's an issue. I've redrawn it and also tuned the lowercase k a bit. Here it is, together with the sharp s from your other issue

<img width="576" alt="image" src="https://user-images.githubusercontent.com/1328396/189533918-bf4c05c8-b419-4a83-8821-5d6d192387e9.png">
