### ISSUE TITLE
Inconsistent character heights when using otf in Windows

### ISSUE THREAD

**Issue by madmalik** [madmalik/mononoki#94]
The heights of some lower case characters are inconsistent. This happens for the otf version, but not the ttf version.

See https://github.com/madmalik/mononoki/issues/79#issuecomment-1243626971

**Comment by datMaffin** [comment]
I am able to reproduce the issue: 
![image](https://user-images.githubusercontent.com/29998721/198849837-66cb7927-f1cf-40e5-8b78-237d08dd1640.png)


Looking at the affected letters (`u` and `e`) from the otf in FontForge, reveals that the hinting of both of them is weird

- `u`: The horizontal hints at the top are too high:
![image](https://user-images.githubusercontent.com/29998721/198849894-99e685a9-b7e8-454f-a32e-3807563a010c.png)
- `e`: There seems to be no hinting information at all:
![image](https://user-images.githubusercontent.com/29998721/198849935-808728f1-8dab-4cb4-b9e3-59adcbf63f3b.png)

For comparison, this is how fontforge sees the `n`, which seems to render fine:
![image](https://user-images.githubusercontent.com/29998721/198849976-0d450ea5-7f55-4ce9-91ab-f7a3df0f4fe6.png)

**Comment by madmalik** [comment]
There where some issues with he hinting. I since corrected it, but I didn't close the issue because I hadn't tested it on windows yet. But the next version I'll upload will have the correct hints
