### ISSUE TITLE
Cyrillic "б" (lowercase be) and digit "6" are hard to distinguish

### ISSUE THREAD

**Issue by yuki0iq** [madmalik/mononoki#96]
![image](https://user-images.githubusercontent.com/44705138/200361936-0c4e26cc-bdf9-4240-8cc9-8fcc1f3dfa69.png)
text on image: 6б6б6б6 (six, be, six, be, six, be, six)

these characters look way too similar...

**Comment by madmalik** [comment]
I have adjusted the Cyrillic be to be more distinct. This is what it looks like now compared to the 6.
<img width="276" alt="image" src="https://user-images.githubusercontent.com/1328396/202855270-586de78d-8cd9-43e9-9fb7-64dcc5be380d.png">
