### ISSUE TITLE
Brew Error: font-mononoki: SHA256 mismatch

### ISSUE THREAD

**Issue by HacKanCuBa** [madmalik/mononoki#98]
Since the latest release, I keep getting the following error while upgrading this:

```
...:~$ brew upgrade font-mononoki
==> Upgrading 1 outdated package:
font-mononoki 1.4 -> 1.5
==> Upgrading font-mononoki
==> Downloading https://github.com/madmalik/mononoki/releases/download/1.5/mononoki.zip
Already downloaded: /Users/ivan/Library/Caches/Homebrew/downloads/b7e3dbd9cb35cd9aa1cb1dcb934998cb6b3919f59dcc234274891f6d201394e6--mononoki.zip
==> Purging files for version 1.5 of Cask font-mononoki
Error: font-mononoki: SHA256 mismatch
Expected: c5bc01793b506bcbbfaefbe0a7e49021511d19077d35db934303ecf454fb3c46
  Actual: 2159f39e133802f48f5a13863e63a3c66bcd316ff112ca74c23d7428007f9e6b
    File: /Users/ivan/Library/Caches/Homebrew/downloads/b7e3dbd9cb35cd9aa1cb1dcb934998cb6b3919f59dcc234274891f6d201394e6--mononoki.zip
To retry an incomplete download, remove the file above.
```

Of course I already tried removing the file, but it fails again. I also did `cleanup`, prune and scrub of the cache, so it looks like an upstream issue.

**Comment by felis-blue** [comment]
@madmalik and I found that there were some glyphs that were rendered incorrectly after originally publishing version 1.5, so we deleted the original 1.5 release after a couple of hours and then rereleased with the fixed glyphs. It looks like the homebrew formula (https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-mononoki.rb) has the wrong SHA hash. @madmalik will submit a pull request to them to fix the hash!

**Comment by HacKanCuBa** [comment]
Thanks, keep up the good work!!
BTW, consider using patch versions for that, releasing 1.5.1 would have solved it too :)

**Comment by felis-blue** [comment]
Yeah, we would have preferred to use a patch version, unfortunately the software that @madmalik uses (Glyphs) does not support patch versions, which is why we decided to rerelease.

**Comment by felis-blue** [comment]
The pull request has been merged, you should be able to update now!
